// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using e_violenciagen.Data;

#nullable disable

namespace e_violenciagen.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903230341_AddViolenciaCases")]
    partial class AddViolenciaCases
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonaInstitucion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cargo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("CodigoProfesional")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<Guid>("InstitucionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InstitucionId1")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UnidadOrganizativaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UnidadOrganizativaId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("InstitucionId1");

                    b.HasIndex("PersonaId");

                    b.HasIndex("UnidadOrganizativaId");

                    b.HasIndex("UnidadOrganizativaId1");

                    b.ToTable("PersonasInstituciones");
                });

            modelBuilder.Entity("e_violenciagen.Models.Barrio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DistritoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DistritoId");

                    b.ToTable("Barrios");
                });

            modelBuilder.Entity("e_violenciagen.Models.Caso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BarrioHechoId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoCaso")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("EstadoCasoId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("FechaHecho")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LugarDescripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RelatoInicial")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Resumen")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BarrioHechoId");

                    b.HasIndex("CodigoCaso")
                        .IsUnique();

                    b.HasIndex("EstadoCasoId");

                    b.HasIndex("FechaRegistro");

                    b.ToTable("Casos");
                });

            modelBuilder.Entity("e_violenciagen.Models.CasoTipoViolencia", b =>
                {
                    b.Property<Guid>("CasoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TipoViolenciaId")
                        .HasColumnType("uuid");

                    b.HasKey("CasoId", "TipoViolenciaId");

                    b.HasIndex("TipoViolenciaId");

                    b.ToTable("CasosTiposViolencia");
                });

            modelBuilder.Entity("e_violenciagen.Models.Distrito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProvinciaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Distritos");
                });

            modelBuilder.Entity("e_violenciagen.Models.EstadoCaso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("EstadosCaso");
                });

            modelBuilder.Entity("e_violenciagen.Models.Institucion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Siglas")
                        .HasColumnType("text");

                    b.Property<Guid>("TipoInstitucionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TipoInstitucionId");

                    b.ToTable("Instituciones");
                });

            modelBuilder.Entity("e_violenciagen.Models.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("BarrioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombres")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<Guid?>("TipoDocumentoIdentidadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BarrioId");

                    b.HasIndex("TipoDocumentoIdentidadId", "NumeroDocumento")
                        .IsUnique();

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("e_violenciagen.Models.Provincia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("e_violenciagen.Models.TipoActuacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TiposActuacion");
                });

            modelBuilder.Entity("e_violenciagen.Models.TipoDocumentoExpediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TiposDocumentoExpediente");
                });

            modelBuilder.Entity("e_violenciagen.Models.TipoDocumentoIdentidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TiposDocumentoIdentidad");
                });

            modelBuilder.Entity("e_violenciagen.Models.TipoInstitucion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TiposInstitucion");
                });

            modelBuilder.Entity("e_violenciagen.Models.TipoViolencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TiposViolencia");
                });

            modelBuilder.Entity("e_violenciagen.Models.UnidadOrganizativa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<Guid>("InstitucionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UnidadPadreId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("UnidadPadreId");

                    b.ToTable("UnidadesOrganizativas");
                });

            modelBuilder.Entity("PersonaInstitucion", b =>
                {
                    b.HasOne("e_violenciagen.Models.Institucion", "Institucion")
                        .WithMany()
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("e_violenciagen.Models.Institucion", null)
                        .WithMany("PersonasVinculadas")
                        .HasForeignKey("InstitucionId1");

                    b.HasOne("e_violenciagen.Models.Persona", "Persona")
                        .WithMany("VinculacionesInstitucionales")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("e_violenciagen.Models.UnidadOrganizativa", "UnidadOrganizativa")
                        .WithMany()
                        .HasForeignKey("UnidadOrganizativaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("e_violenciagen.Models.UnidadOrganizativa", null)
                        .WithMany("PersonasVinculadas")
                        .HasForeignKey("UnidadOrganizativaId1")
                        .HasConstraintName("FK_PersonasInstituciones_UnidadesOrganizativas_UnidadOrganiza~1");

                    b.Navigation("Institucion");

                    b.Navigation("Persona");

                    b.Navigation("UnidadOrganizativa");
                });

            modelBuilder.Entity("e_violenciagen.Models.Barrio", b =>
                {
                    b.HasOne("e_violenciagen.Models.Distrito", "Distrito")
                        .WithMany("Barrios")
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("e_violenciagen.Models.Caso", b =>
                {
                    b.HasOne("e_violenciagen.Models.Barrio", "BarrioHecho")
                        .WithMany()
                        .HasForeignKey("BarrioHechoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("e_violenciagen.Models.EstadoCaso", "EstadoCaso")
                        .WithMany("Casos")
                        .HasForeignKey("EstadoCasoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BarrioHecho");

                    b.Navigation("EstadoCaso");
                });

            modelBuilder.Entity("e_violenciagen.Models.CasoTipoViolencia", b =>
                {
                    b.HasOne("e_violenciagen.Models.Caso", "Caso")
                        .WithMany("TiposViolencia")
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_violenciagen.Models.TipoViolencia", "TipoViolencia")
                        .WithMany("Casos")
                        .HasForeignKey("TipoViolenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caso");

                    b.Navigation("TipoViolencia");
                });

            modelBuilder.Entity("e_violenciagen.Models.Distrito", b =>
                {
                    b.HasOne("e_violenciagen.Models.Provincia", "Provincia")
                        .WithMany("Distritos")
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("e_violenciagen.Models.Institucion", b =>
                {
                    b.HasOne("e_violenciagen.Models.TipoInstitucion", "TipoInstitucion")
                        .WithMany("Instituciones")
                        .HasForeignKey("TipoInstitucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoInstitucion");
                });

            modelBuilder.Entity("e_violenciagen.Models.Persona", b =>
                {
                    b.HasOne("e_violenciagen.Models.Barrio", "Barrio")
                        .WithMany()
                        .HasForeignKey("BarrioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("e_violenciagen.Models.TipoDocumentoIdentidad", "TipoDocumentoIdentidad")
                        .WithMany("Personas")
                        .HasForeignKey("TipoDocumentoIdentidadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Barrio");

                    b.Navigation("TipoDocumentoIdentidad");
                });

            modelBuilder.Entity("e_violenciagen.Models.UnidadOrganizativa", b =>
                {
                    b.HasOne("e_violenciagen.Models.Institucion", "Institucion")
                        .WithMany()
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_violenciagen.Models.UnidadOrganizativa", "UnidadPadre")
                        .WithMany("UnidadesHijas")
                        .HasForeignKey("UnidadPadreId");

                    b.Navigation("Institucion");

                    b.Navigation("UnidadPadre");
                });

            modelBuilder.Entity("e_violenciagen.Models.Caso", b =>
                {
                    b.Navigation("TiposViolencia");
                });

            modelBuilder.Entity("e_violenciagen.Models.Distrito", b =>
                {
                    b.Navigation("Barrios");
                });

            modelBuilder.Entity("e_violenciagen.Models.EstadoCaso", b =>
                {
                    b.Navigation("Casos");
                });

            modelBuilder.Entity("e_violenciagen.Models.Institucion", b =>
                {
                    b.Navigation("PersonasVinculadas");
                });

            modelBuilder.Entity("e_violenciagen.Models.Persona", b =>
                {
                    b.Navigation("VinculacionesInstitucionales");
                });

            modelBuilder.Entity("e_violenciagen.Models.Provincia", b =>
                {
                    b.Navigation("Distritos");
                });

            modelBuilder.Entity("e_violenciagen.Models.TipoDocumentoIdentidad", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("e_violenciagen.Models.TipoInstitucion", b =>
                {
                    b.Navigation("Instituciones");
                });

            modelBuilder.Entity("e_violenciagen.Models.TipoViolencia", b =>
                {
                    b.Navigation("Casos");
                });

            modelBuilder.Entity("e_violenciagen.Models.UnidadOrganizativa", b =>
                {
                    b.Navigation("PersonasVinculadas");

                    b.Navigation("UnidadesHijas");
                });
#pragma warning restore 612, 618
        }
    }
}
