// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using e_violenciagen.Data;

#nullable disable

namespace e_violenciagen.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260912115115_AddFotoToPersona")]
    partial class AddFotoToPersona
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("CasoCodigoSequence");

            modelBuilder.Entity("PersonaInstitucion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cargo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("CodigoProfesional")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<Guid>("InstitucionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InstitucionId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UnidadOrganizativaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UnidadOrganizativaId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("InstitucionId1");

                    b.HasIndex("PersonaId");

                    b.HasIndex("UnidadOrganizativaId");

                    b.HasIndex("UnidadOrganizativaId1");

                    b.ToTable("PersonasInstituciones");
                });

            modelBuilder.Entity("e_violenciagen.Models.Actuacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CasoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("FechaActuacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InstitucionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resultado")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("TipoActuacionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid?>("UnidadOrganizativaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("TipoActuacionId");

                    b.HasIndex("UnidadOrganizativaId");

                    b.HasIndex("CasoId", "FechaActuacion");

                    b.ToTable("Actuaciones");
                });

            modelBuilder.Entity("e_violenciagen.Models.ActuacionParticipante", b =>
                {
                    b.Property<Guid>("ActuacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonaInstitucionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EsResponsable")
                        .HasColumnType("boolean");

                    b.Property<string>("RolEnActuacion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("ActuacionId", "PersonaInstitucionId");

                    b.HasIndex("PersonaInstitucionId");

                    b.ToTable("ActuacionesParticipantes");
                });

            modelBuilder.Entity("e_violenciagen.Models.Barrio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DistritoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DistritoId");

                    b.ToTable("Barrios");
                });

            modelBuilder.Entity("e_violenciagen.Models.Caso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("BarrioHechoId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoCaso")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("EstadoCasoId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("FechaHecho")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LugarDescripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RelatoInicial")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Resumen")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BarrioHechoId");

                    b.HasIndex("CodigoCaso")
                        .IsUnique();

                    b.HasIndex("EstadoCasoId");

                    b.HasIndex("FechaRegistro");

                    b.ToTable("Casos");
                });

            modelBuilder.Entity("e_violenciagen.Models.CasoPresuntoAgresor", b =>
                {
                    b.Property<Guid>("CasoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaVinculacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RelacionConVictima")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CasoId", "PersonaId");

                    b.HasIndex("PersonaId");

                    b.ToTable("CasosPresuntosAgresores");
                });

            modelBuilder.Entity("e_violenciagen.Models.CasoTipoViolencia", b =>
                {
                    b.Property<Guid>("CasoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TipoViolenciaId")
                        .HasColumnType("uuid");

                    b.HasKey("CasoId", "TipoViolenciaId");

                    b.HasIndex("TipoViolenciaId");

                    b.ToTable("CasosTiposViolencia");
                });

            modelBuilder.Entity("e_violenciagen.Models.CasoVictima", b =>
                {
                    b.Property<Guid>("CasoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EsVictimaPrincipal")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaVinculacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("RequiereProteccion")
                        .HasColumnType("boolean");

                    b.HasKey("CasoId", "PersonaId");

                    b.HasIndex("PersonaId");

                    b.ToTable("CasosVictimas");
                });

            modelBuilder.Entity("e_violenciagen.Models.Distrito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProvinciaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Distritos");
                });

            modelBuilder.Entity("e_violenciagen.Models.DocumentoExpediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ActuacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CasoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("EsConfidencial")
                        .HasColumnType("boolean");

                    b.Property<string>("Extension")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("FechaDocumento")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaIncorporacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashArchivo")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NombreAlmacenado")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NombreOriginal")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RutaAlmacenamiento")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TipoDocumentoExpedienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoMime")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Titulo")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActuacionId");

                    b.HasIndex("CasoId");

                    b.HasIndex("HashArchivo");

                    b.HasIndex("RutaAlmacenamiento")
                        .IsUnique();

                    b.HasIndex("TipoDocumentoExpedienteId");

                    b.ToTable("DocumentosExpediente");
                });

            modelBuilder.Entity("e_violenciagen.Models.EstadoCaso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("EstadosCaso");
                });

            modelBuilder.Entity("e_violenciagen.Models.Institucion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Siglas")
                        .HasColumnType("text");

                    b.Property<Guid>("TipoInstitucionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TipoInstitucionId");

                    b.ToTable("Instituciones");
                });

            modelBuilder.Entity("e_violenciagen.Models.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("BarrioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombres")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<Guid?>("TipoDocumentoIdentidadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BarrioId");

                    b.HasIndex("TipoDocumentoIdentidadId", "NumeroDocumento")
                        .IsUnique();

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("e_violenciagen.Models.Provincia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("e_violenciagen.Models.TipoActuacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TiposActuacion");
                });

            modelBuilder.Entity("e_violenciagen.Models.TipoDocumentoExpediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TiposDocumentoExpediente");
                });

            modelBuilder.Entity("e_violenciagen.Models.TipoDocumentoIdentidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TiposDocumentoIdentidad");
                });

            modelBuilder.Entity("e_violenciagen.Models.TipoInstitucion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TiposInstitucion");
                });

            modelBuilder.Entity("e_violenciagen.Models.TipoViolencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TiposViolencia");
                });

            modelBuilder.Entity("e_violenciagen.Models.UnidadOrganizativa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<Guid>("InstitucionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<Guid?>("UnidadPadreId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("UnidadPadreId");

                    b.ToTable("UnidadesOrganizativas");
                });

            modelBuilder.Entity("PersonaInstitucion", b =>
                {
                    b.HasOne("e_violenciagen.Models.Institucion", "Institucion")
                        .WithMany()
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("e_violenciagen.Models.Institucion", null)
                        .WithMany("PersonasVinculadas")
                        .HasForeignKey("InstitucionId1");

                    b.HasOne("e_violenciagen.Models.Persona", "Persona")
                        .WithMany("VinculacionesInstitucionales")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("e_violenciagen.Models.UnidadOrganizativa", "UnidadOrganizativa")
                        .WithMany()
                        .HasForeignKey("UnidadOrganizativaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("e_violenciagen.Models.UnidadOrganizativa", null)
                        .WithMany("PersonasVinculadas")
                        .HasForeignKey("UnidadOrganizativaId1")
                        .HasConstraintName("FK_PersonasInstituciones_UnidadesOrganizativas_UnidadOrganiza~1");

                    b.Navigation("Institucion");

                    b.Navigation("Persona");

                    b.Navigation("UnidadOrganizativa");
                });

            modelBuilder.Entity("e_violenciagen.Models.Actuacion", b =>
                {
                    b.HasOne("e_violenciagen.Models.Caso", "Caso")
                        .WithMany("Actuaciones")
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_violenciagen.Models.Institucion", "Institucion")
                        .WithMany("Actuaciones")
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("e_violenciagen.Models.TipoActuacion", "TipoActuacion")
                        .WithMany("Actuaciones")
                        .HasForeignKey("TipoActuacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("e_violenciagen.Models.UnidadOrganizativa", "UnidadOrganizativa")
                        .WithMany("Actuaciones")
                        .HasForeignKey("UnidadOrganizativaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Caso");

                    b.Navigation("Institucion");

                    b.Navigation("TipoActuacion");

                    b.Navigation("UnidadOrganizativa");
                });

            modelBuilder.Entity("e_violenciagen.Models.ActuacionParticipante", b =>
                {
                    b.HasOne("e_violenciagen.Models.Actuacion", "Actuacion")
                        .WithMany("Participantes")
                        .HasForeignKey("ActuacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonaInstitucion", "PersonaInstitucion")
                        .WithMany("ParticipacionesActuaciones")
                        .HasForeignKey("PersonaInstitucionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actuacion");

                    b.Navigation("PersonaInstitucion");
                });

            modelBuilder.Entity("e_violenciagen.Models.Barrio", b =>
                {
                    b.HasOne("e_violenciagen.Models.Distrito", "Distrito")
                        .WithMany("Barrios")
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("e_violenciagen.Models.Caso", b =>
                {
                    b.HasOne("e_violenciagen.Models.Barrio", "BarrioHecho")
                        .WithMany()
                        .HasForeignKey("BarrioHechoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("e_violenciagen.Models.EstadoCaso", "EstadoCaso")
                        .WithMany("Casos")
                        .HasForeignKey("EstadoCasoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BarrioHecho");

                    b.Navigation("EstadoCaso");
                });

            modelBuilder.Entity("e_violenciagen.Models.CasoPresuntoAgresor", b =>
                {
                    b.HasOne("e_violenciagen.Models.Caso", "Caso")
                        .WithMany("PresuntosAgresores")
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_violenciagen.Models.Persona", "Persona")
                        .WithMany("CasosComoPresuntoAgresor")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caso");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("e_violenciagen.Models.CasoTipoViolencia", b =>
                {
                    b.HasOne("e_violenciagen.Models.Caso", "Caso")
                        .WithMany("TiposViolencia")
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_violenciagen.Models.TipoViolencia", "TipoViolencia")
                        .WithMany("Casos")
                        .HasForeignKey("TipoViolenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caso");

                    b.Navigation("TipoViolencia");
                });

            modelBuilder.Entity("e_violenciagen.Models.CasoVictima", b =>
                {
                    b.HasOne("e_violenciagen.Models.Caso", "Caso")
                        .WithMany("Victimas")
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_violenciagen.Models.Persona", "Persona")
                        .WithMany("CasosComoVictima")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caso");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("e_violenciagen.Models.Distrito", b =>
                {
                    b.HasOne("e_violenciagen.Models.Provincia", "Provincia")
                        .WithMany("Distritos")
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("e_violenciagen.Models.DocumentoExpediente", b =>
                {
                    b.HasOne("e_violenciagen.Models.Actuacion", "Actuacion")
                        .WithMany("Documentos")
                        .HasForeignKey("ActuacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("e_violenciagen.Models.Caso", "Caso")
                        .WithMany("Documentos")
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_violenciagen.Models.TipoDocumentoExpediente", "TipoDocumentoExpediente")
                        .WithMany("Documentos")
                        .HasForeignKey("TipoDocumentoExpedienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actuacion");

                    b.Navigation("Caso");

                    b.Navigation("TipoDocumentoExpediente");
                });

            modelBuilder.Entity("e_violenciagen.Models.Institucion", b =>
                {
                    b.HasOne("e_violenciagen.Models.TipoInstitucion", "TipoInstitucion")
                        .WithMany("Instituciones")
                        .HasForeignKey("TipoInstitucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoInstitucion");
                });

            modelBuilder.Entity("e_violenciagen.Models.Persona", b =>
                {
                    b.HasOne("e_violenciagen.Models.Barrio", "Barrio")
                        .WithMany()
                        .HasForeignKey("BarrioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("e_violenciagen.Models.TipoDocumentoIdentidad", "TipoDocumentoIdentidad")
                        .WithMany("Personas")
                        .HasForeignKey("TipoDocumentoIdentidadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Barrio");

                    b.Navigation("TipoDocumentoIdentidad");
                });

            modelBuilder.Entity("e_violenciagen.Models.UnidadOrganizativa", b =>
                {
                    b.HasOne("e_violenciagen.Models.Institucion", "Institucion")
                        .WithMany()
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_violenciagen.Models.UnidadOrganizativa", "UnidadPadre")
                        .WithMany("UnidadesHijas")
                        .HasForeignKey("UnidadPadreId");

                    b.Navigation("Institucion");

                    b.Navigation("UnidadPadre");
                });

            modelBuilder.Entity("PersonaInstitucion", b =>
                {
                    b.Navigation("ParticipacionesActuaciones");
                });

            modelBuilder.Entity("e_violenciagen.Models.Actuacion", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("e_violenciagen.Models.Caso", b =>
                {
                    b.Navigation("Actuaciones");

                    b.Navigation("Documentos");

                    b.Navigation("PresuntosAgresores");

                    b.Navigation("TiposViolencia");

                    b.Navigation("Victimas");
                });

            modelBuilder.Entity("e_violenciagen.Models.Distrito", b =>
                {
                    b.Navigation("Barrios");
                });

            modelBuilder.Entity("e_violenciagen.Models.EstadoCaso", b =>
                {
                    b.Navigation("Casos");
                });

            modelBuilder.Entity("e_violenciagen.Models.Institucion", b =>
                {
                    b.Navigation("Actuaciones");

                    b.Navigation("PersonasVinculadas");
                });

            modelBuilder.Entity("e_violenciagen.Models.Persona", b =>
                {
                    b.Navigation("CasosComoPresuntoAgresor");

                    b.Navigation("CasosComoVictima");

                    b.Navigation("VinculacionesInstitucionales");
                });

            modelBuilder.Entity("e_violenciagen.Models.Provincia", b =>
                {
                    b.Navigation("Distritos");
                });

            modelBuilder.Entity("e_violenciagen.Models.TipoActuacion", b =>
                {
                    b.Navigation("Actuaciones");
                });

            modelBuilder.Entity("e_violenciagen.Models.TipoDocumentoExpediente", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("e_violenciagen.Models.TipoDocumentoIdentidad", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("e_violenciagen.Models.TipoInstitucion", b =>
                {
                    b.Navigation("Instituciones");
                });

            modelBuilder.Entity("e_violenciagen.Models.TipoViolencia", b =>
                {
                    b.Navigation("Casos");
                });

            modelBuilder.Entity("e_violenciagen.Models.UnidadOrganizativa", b =>
                {
                    b.Navigation("Actuaciones");

                    b.Navigation("PersonasVinculadas");

                    b.Navigation("UnidadesHijas");
                });
#pragma warning restore 612, 618
        }
    }
}
